// Fields needed for administration/trash operations. Keep this explicit so
// older deployed databases without the optional interpretation column remain usable.
export const calculationWithoutInterpretationSelect = {
  id: true,
  userId: true,
  publicId: true,
  saved: true,
  type: true,
  name1: true,
  date1: true,
  time1: true,
  place1: true,
  lat1: true,
  lon1: true,
  tz1: true,
  name2: true,
  date2: true,
  time2: true,
  place2: true,
  lat2: true,
  lon2: true,
  tz2: true,
  transitDate: true,
  houseSystem: true,
  ipAddress: true,
  userAgent: true,
  resultJson: true,
  updatedAt: true,
  createdAt: true,
} as const;
